version: '3.8'

services:

  mysql3:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'monitoring_values'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3309:3306"
    volumes:
      - my-db3:/var/lib/mysql
    networks:
      demo_net:

  rabbitmq1:
    container_name: rabbitmq1
    hostname: rabbitmq1
    image: "rabbitmq:3.12.12-management"
    ports:
        - "5673:5672"
        - "15673:15672"
    volumes:
        - 'rabbitmq_data:/data'

    networks:
      demo_net:

  monitoring:
    image: monitoring-image
    hostname: monitoring-ms
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=mysql3
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=monitoring_values
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - RABBITMQ_HOST=rabbitmq1
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq1
    networks:
      demo_net:

volumes:
  my-db3:
  rabbitmq_data:

networks:
  demo_net:
    external: true
